export const projects = [
  {
    src: '/images/project-1.jpg',
    title: 'Autodesk',
    desc: 'Amsterdam - RAI Exhibition Centre',
    alt: 'Project - Autodesk',
    link: '/',
  },
  {
    src: '/images/project-2.jpg',
    title: 'Microsoft',
    desc: 'San Francisco - Moscone Centre',
    alt: 'Project - Microsoft',
    link: '/',
  },
  {
    src: '/images/project-3.jpg',
    title: 'Open AI',
    desc: 'Birmingham - NEC Exhibition Centre',
    alt: 'Project - Open AI',
    link: '/',
  },
  {
    src: '/images/project-4.jpg',
    title: 'Adobe',
    desc: 'New York',
    alt: 'Project - Adobe',
    link: '/',
  },
  {
    src: '/images/project-5.jpg',
    title: 'Google',
    desc: 'London - Google UK HQ',
    alt: 'Project - Google',
    link: '/',
  },
  {
    src: '/images/project-6.jpg',
    title: 'Hiscox',
    desc: "London - Lloyd's Building",
    alt: 'Project - Hiscox',
    link: '/',
  },
  {
    src: '/images/project-7.jpg',
    title: 'Mahou San Miguel',
    desc: 'Madrid',
    alt: 'Project - Mahou San Miguel',
    link: '/',
  },
  {
    src: '/images/project-8.jpg',
    title: 'Twilio',
    desc: 'London - ExCel',
    alt: 'Project - Twilio',
    link: '/',
  },
  {
    src: '/images/project-9.jpg',
    title: 'Reddit',
    desc: 'Hamburg Exhibition Centre',
    alt: 'Project - Reddit',
    link: '/',
  },
]
