export const projects = [
  {
    src: '/images/project-1.jpg',
    title: 'Autodesk',
    desc: 'New York',
    alt: 'Image 1',
    link: '/projects/autodesk',
  },
  {
    src: '/images/project-2.jpg',
    title: 'BAE',
    desc: 'UK RAF Bases',
    alt: 'Image 2',
    link: '/projects/bae',
  },
  {
    src: '/images/project-3.jpg',
    title: 'Cialis',
    desc: "London - King's Cross Station",
    alt: 'Image 3',
    link: '/projects/cialis',
  },
  {
    src: '/images/project-4.jpg',
    title: 'Fireblocks',
    desc: 'New York',
    alt: 'Image 4',
    link: '/projects/fireblocks',
  },
  {
    src: '/images/project-5.jpg',
    title: 'Google',
    desc: 'London - Google UK HQ',
    alt: 'Image 5',
    link: '/projects/google',
  },
  {
    src: '/images/project-6.jpg',
    title: 'Hiscox',
    desc: "London - Lloyd's Building",
    alt: 'Image 5',
    link: '/projects/hiscox',
  },
  {
    src: '/images/project-7.jpg',
    title: 'Mahou San Miguel',
    desc: 'Madrid',
    alt: 'Image 5',
    link: '/projects/mahou-san-miguel',
  },
  {
    src: '/images/project-8.jpg',
    title: 'QinetiQ',
    desc: 'London - ExCel',
    alt: 'Image 5',
    link: '/projects/qinetiq',
  },
  {
    src: '/images/project-9.jpg',
    title: 'Reddit',
    desc: 'Hamburg Exhibition Centre',
    alt: 'Image 5',
    link: '/projects/reddit',
  },
]
